export default {
  ACTION: {
    CHANGE_PAGE: 'CHANGE_PAGE',
    CHANGE_SIZE: 'CHANGE_SIZE',
    APPLY_FILTER: 'APPLY_FILTER',
    RELOAD_DATA: 'RELOAD_DATA',
    RESET_FILTER: 'RESET_FILTER',
    CHANGE_DISPLAY_PAGE: 'CHANGE_DISPLAY_PAGE',
  },
  DATA_TABLE: {
    ROW_PER_PAGE: 20,
  },
  REACT_QUERY: {
    CODES: {
      SUCCESS: 'success',
      LOADING: 'loading',
      ERROR: 'error',
    },
    KEYS: {
      RQ_GET_AUTO_CALL_LIST: 'RQ_GET_AUTO_CALL_LIST',
      RQ_GET_AUTO_CALL_BY_ID: 'RQ_GET_AUTO_CALL_BY_ID',

      RQ_GET_CAMPAIGN_BY_ID: 'RQ_GET_CAMPAIGN_BY_ID',
      RQ_GET_CAMPAIGN_LIST: 'RQ_GET_CAMPAIGN_LIST',
      RQ_GET_CAMPAIGN_LIST_ALL: 'RQ_GET_CAMPAIGN_LIST_ALL',

      RQ_GET_CALL_LIST: 'RQ_GET_CALL_LIST',
      RQ_GET_CALL_OF_SALE: 'RQ_GET_CALL_OF_SALE',

      RQ_GET_COMMENT_LIST: 'RQ_GET_COMMENT_LIST',

      RQ_GET_CONFIG_LIST: 'RQ_GET_CONFIG_LIST',
      RQ_GET_CONFIG_BY_ID: 'RQ_GET_CONFIG_BY_ID',
      RQ_GET_CONFIG_CAMPAIGN_GROUP_LIST: 'RQ_GET_CONFIG_CAMPAIGN_GROUP_LIST',
      RQ_GET_CONFIG_CAMPAIGN_TYPE_LIST: 'RQ_GET_CONFIG_CAMPAIGN_TYPE_LIST',
      RQ_GET_CONFIG_PRODUCT_LIST: 'RQ_GET_CONFIG_PRODUCT_LIST',
      RQ_GET_CONFIG_SALE_TYPE_LIST: 'RQ_GET_CONFIG_SALE_TYPE_LIST',
      RQ_GET_CONFIG_SHIPMENT_LIST: 'RQ_GET_CONFIG_SHIPMENT_LIST',
      RQ_GET_CONFIG_SHIPMENT_GIFT_LIST: 'RQ_GET_CONFIG_SHIPMENT_GIFT_LIST',
      RQ_GET_CONFIG_SOURCE_TYPE_LIST: 'RQ_GET_CONFIG_SOURCE_TYPE_LIST',
      RQ_GET_CONFIG_UTM_MEDIUM_LIST: 'RQ_GET_CONFIG_UTM_MEDIUM_LIST',
      RQ_GET_CONFIG_UTM_SOURCE_LIST: 'RQ_GET_CONFIG_UTM_SOURCE_LIST',
      RQ_GET_CONFIG_UTM_TEAM_LIST: 'RQ_GET_CONFIG_UTM_TEAM_LIST',

      RQ_GET_CODE_ACTIVE: 'RQ_GET_CODE_ACTIVE',

      RQ_GET_CONTACT_BY_ID: 'RQ_GET_CONTACT_BY_ID',
      RQ_GET_CONTACT_LIST: 'EQ_GET_CONTACT_LIST',

      RQ_GET_DASHBOARD: 'RQ_GET_DASHBOARD',

      RQ_GET_DEAL_BY_ID: 'RQ_GET_DEAL_BY_ID',
      RQ_GET_DEAL_LIST: 'RQ_GET_DEAL_LIST',
      RQ_GET_DEAL_PACKAGE_LIST: 'RQ_GET_DEAL_PACKAGE_LIST',

      RQ_GET_DEPARTMENT_ALL: 'RQ_GET_DEPARTMENT_ALL',
      RQ_GET_DEPARTMENT_BY_ID: 'RQ_GET_DEPARTMENT_BY_ID',
      RQ_GET_DEPARTMENT_BY_TYPE: 'RQ_GET_DEPARTMENT_BY_TYPE',
      RQ_GET_DEPARTMENT_LIST: 'RQ_GET_DEPARTMENT_LIST',
      RQ_GET_USER_BY_DEPARTMENT: 'RQ_GET_USER_BY_DEPARTMENT',

      RQ_GET_DISTRICT_BY_ID: 'RQ_GET_DISTRICT_BY_ID',
      RQ_GET_DISTRICT_LIST: 'RQ_GET_DISTRICT_LIST',

      RQ_LOGIN: 'RQ_LOGIN',

      RQ_GET_PACKAGE_LIST: 'RQ_GET_PACKAGE_LIST',
      RQ_GET_PACKAGE_BY_ID: 'RQ_GET_PACKAGE_BY_ID',

      RQ_GET_PERMISSION_LIST: 'RQ_GET_PERMISSION_LIST',
      RQ_GET_PERMISSION_BY_ID: 'RQ_GET_PERMISSION_BY_ID',
      RQ_GET_PERMISSION_OF_ROLE_BY_ID: 'RQ_GET_PERMISSION_OF_ROLE_BY_ID',
      RQ_GET_PERMISSION_OF_USER_BY_ID: 'RQ_GET_PERMISSION_OF_USER_BY_ID',

      RQ_GET_PIPE_LIST: 'RQ_GET_PIPE_LIST',
      RQ_GET_PIPELINE_BY_ID: 'RQ_GET_PIPELINE_BY_ID',

      RQ_GET_PROVINCE_BY_ID: 'RQ_GET_PROVINCE_BY_ID',
      RQ_GET_PROVINCE_LIST: 'RQ_GET_PROVINCE_LIST',

      RQ_GET_ROLE_BY_ID: 'RQ_GET_ROLE_BY_ID',
      RQ_GET_ROLE_LIST: 'RQ_GET_ROLE_LIST',
      RQ_GET_ROLE_OF_USER_BY_ID: 'RQ_GET_ROLE_OF_USER_BY_ID',

      RQ_GET_SMS_LIST: 'RQ_GET_SMS_LIST',
      RQ_GET_SMS_HISTORY_LIST: 'RQ_GET_SMS_HISTORY_LIST',
      RQ_GET_SMS_FILTER: 'RQ_GET_SMS_FILTER',

      RQ_GET_SHIPMENT_LIST: 'RQ_GET_SHIPMENT_LIST',
      RQ_GET_SHIPMENT_BY_ID: 'RQ_GET_SHIPMENT_BY_ID',

      RQ_GET_STAGE_LIST: 'RQ_GET_STAGE_LIST',
      RQ_GET_STAGE_BY_ID: 'RQ_GET_STAGE_BY_ID',
      RQ_GET_STAGE_OF_PIPELINE_BY_ID: 'RQ_GET_STAGE_OF_PIPELINE_BY_ID',

      RQ_GET_TICKET_BY_ID: 'RQ_GET_TICKET_BY_ID',
      RQ_GET_TICKET_LIST: 'RQ_GET_TICKET_LIST',
      RQ_GET_TICKET_TYPE_BY_ID: 'RQ_GET_TICKET_BY_ID',
      RQ_GET_TICKET_TYPE_LIST: 'RQ_GET_TICKET_LIST',

      RQ_GET_VOUCHER_BY_ID: 'RQ_GET_VOUCHER_BY_ID',

      RQ_GET_USER_BY_ID: 'RQ_GET_USER_BY_ID',
      RQ_GET_USER_LIST: 'RQ_GET_USER_LIST',
      RQ_GET_DEPARTMENT_BY_ID_OF_USER: 'RQ_GET_DEPARTMENT_BY_ID_OF_USER',
    },
  },
  SEED: {
    SELECTED_THEME: 'SELECTED_THEME',
  },
  PAGES: {
    COMMON: {
      GENDER: ['MALE', 'FEMALE', 'NONE'],
    },
    REPORT: {
      CYCLE: ['BY_DAY', 'FROM_FIRST_DAY_OF_MONTH', 'BY_WEEK'],
      DATA_TYPE: ['NEW_SALE', 'EXTEND', 'UP_SALE', 'EVICTION', 'OTHER'],
    },
    ASSIGN_ALL: {
      TIME_TYPE: ['REGISTERED_DATE', 'UPDATED_DATE', 'ASSIGNED_DATE'],
    },
    TICKET: {
      DEVICE_TYPE: ['PC', 'ANDROID', 'IOS'],
      PRIORITY: ['HIGH', 'MEDIUM', 'LOW'],
      STATUS: ['NEW', 'DONE', 'NOT_LISTEN', 'CALL_LATER', 'TECH_FORWARD', 'VERIFY'],
      // STATUS: ['NEW', 'DONE', 'NOT_LISTEN', 'CALL_LATER', 'SALE_FORWARD', 'TRANSPORT_FORWARD', 'TECH_FORWARD', 'MARKETING_FORWARD', 'VERIFY'],
      SOURCE: ['CALL', 'CALL_MISSED', 'EMAIL', 'CHAT', 'INTERNAL', 'OTHER'],
    },
    CONTACT_DEAL: {
      TIME_TYPE: ['CREATED_DATE', 'REGISTERED_DATE', 'UPDATED_DATE', 'EVICTED_DATE', 'ACTIVATED_DATE', 'EXPIRED_DATE'],
      DEAL_STATUS: ['NEW', 'OPEN', 'WON', 'LOST'],
      PAYMENT_STATUS: ['CUSTOMER_HAS_NOT_PAID', 'CUSTOMER_PAID', 'COMPANY_RECEIVED'],
      PAYMENT_METHOD: ['COD', 'TRANSFER', 'INAPP', 'ONLINE'],
    },
    SHIPMENT: {
      PARTNER: ['EMS', 'VIETTEL_POST'],
      SHIPPING_TYPE: ['PARTNER', 'PARTNER_PROMOTION', 'PROVINCE', 'SOFT_CODE'],
      PAYMENT_METHOD: ['COD', 'TRANSFER'], //, 'INAPP', 'ONLINE'],
      STATUS: ['HAS_NOT_TRANSPORT', 'CLOSE_ORDER', 'BEING_TRANSPORTED', 'SUCCESS_DELIVERY', 'EXPIRED_EXECUTE', 'SALE_EXECUTE', 'DELIVERY_AGAIN', 'RETURN_CONFIRM', 'SUCCESS_RETURN', 'CANCELED'],
    },
    PACKAGE_TYPE: ['BUY_NEW', 'RENEW', 'VHSVN', 'TEST50K'],
    DEPARTMENT: {
      TYPES: ['SALE', 'CUSTOMER_CARE', 'SHIPMENT'],
    },
  },
};
