import RouteValidator from 'src/auth/routes/Validator';
import Head from 'next/head';
import _DealList from 'src/containers/Deal/List/DealList';
import {useTranslation} from 'react-i18next';

export default function DealList() {
    const {t} = useTranslation();
    return (
        <RouteValidator allowedAuthorities={['canListDeal']} authorityKey="permissions">
            <Head>
                <title>{t('helmet.title.deal.list')}</title>
                {/* <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" /> */}
            </Head>
            <_DealList/>
        </RouteValidator>
    )
}